Search.appendIndex(
    [
                {
            "fqsen": "\\Handler\\Handler",
            "name": "Handler",
            "summary": "",
            "url": "classes/Handler-Handler.html"
        },                {
            "fqsen": "\\Handler\\HandlerInterface",
            "name": "HandlerInterface",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method_get"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method_set"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__push\u0028\u0029",
            "name": "__push",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___push"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__pushItems\u0028\u0029",
            "name": "__pushItems",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___pushItems"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__pull\u0028\u0029",
            "name": "__pull",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___pull"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__fill\u0028\u0029",
            "name": "__fill",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___fill"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__clear\u0028\u0029",
            "name": "__clear",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___clear"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__count\u0028\u0029",
            "name": "__count",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___count"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__first\u0028\u0029",
            "name": "__first",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___first"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__last\u0028\u0029",
            "name": "__last",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___last"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__isset\u0028\u0029",
            "name": "__isset",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___isset"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__has\u0028\u0029",
            "name": "__has",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___has"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__find\u0028\u0029",
            "name": "__find",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___find"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__filter\u0028\u0029",
            "name": "__filter",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___filter"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__map\u0028\u0029",
            "name": "__map",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___map"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__merge\u0028\u0029",
            "name": "__merge",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___merge"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__offsetExists\u0028\u0029",
            "name": "__offsetExists",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___offsetExists"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__offsetGet\u0028\u0029",
            "name": "__offsetGet",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___offsetGet"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__offsetSet\u0028\u0029",
            "name": "__offsetSet",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___offsetSet"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__offsetSets\u0028\u0029",
            "name": "__offsetSets",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___offsetSets"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__offsetUnset\u0028\u0029",
            "name": "__offsetUnset",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___offsetUnset"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__offsetUnsets\u0028\u0029",
            "name": "__offsetUnsets",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___offsetUnsets"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__getOffset\u0028\u0029",
            "name": "__getOffset",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___getOffset"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__setOffset\u0028\u0029",
            "name": "__setOffset",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___setOffset"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__getHandler\u0028\u0029",
            "name": "__getHandler",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___getHandler"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__pushHandler\u0028\u0029",
            "name": "__pushHandler",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___pushHandler"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__pushHandlers\u0028\u0029",
            "name": "__pushHandlers",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___pushHandlers"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__pullHandler\u0028\u0029",
            "name": "__pullHandler",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___pullHandler"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__fillHandlers\u0028\u0029",
            "name": "__fillHandlers",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___fillHandlers"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__clearHandlers\u0028\u0029",
            "name": "__clearHandlers",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___clearHandlers"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__getIterator\u0028\u0029",
            "name": "__getIterator",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___getIterator"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__toArray\u0028\u0029",
            "name": "__toArray",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___toArray"
        },                {
            "fqsen": "\\Handler\\HandlerInterface\u003A\u003A__debugInfo\u0028\u0029",
            "name": "__debugInfo",
            "summary": "",
            "url": "classes/Handler-HandlerInterface.html#method___debugInfo"
        },                {
            "fqsen": "\\Handler\\HandlerTrait",
            "name": "HandlerTrait",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___construct"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Retrieves\u0020the\u0020value\u0020of\u0020the\u0020specified\u0020attribute.",
            "url": "classes/Handler-HandlerTrait.html#method_get"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Sets\u0020the\u0020value\u0020of\u0020the\u0020specified\u0020attribute.",
            "url": "classes/Handler-HandlerTrait.html#method_set"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__push\u0028\u0029",
            "name": "__push",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___push"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__pushItems\u0028\u0029",
            "name": "__pushItems",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___pushItems"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__pull\u0028\u0029",
            "name": "__pull",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___pull"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__fill\u0028\u0029",
            "name": "__fill",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___fill"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__clear\u0028\u0029",
            "name": "__clear",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___clear"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__count\u0028\u0029",
            "name": "__count",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___count"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__first\u0028\u0029",
            "name": "__first",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___first"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__last\u0028\u0029",
            "name": "__last",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___last"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__isset\u0028\u0029",
            "name": "__isset",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___isset"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__has\u0028\u0029",
            "name": "__has",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___has"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__find\u0028\u0029",
            "name": "__find",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___find"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__filter\u0028\u0029",
            "name": "__filter",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___filter"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__map\u0028\u0029",
            "name": "__map",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___map"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__merge\u0028\u0029",
            "name": "__merge",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___merge"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__offsetExists\u0028\u0029",
            "name": "__offsetExists",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___offsetExists"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__offsetGet\u0028\u0029",
            "name": "__offsetGet",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___offsetGet"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__offsetSet\u0028\u0029",
            "name": "__offsetSet",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___offsetSet"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__offsetSets\u0028\u0029",
            "name": "__offsetSets",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___offsetSets"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__offsetUnset\u0028\u0029",
            "name": "__offsetUnset",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___offsetUnset"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__offsetUnsets\u0028\u0029",
            "name": "__offsetUnsets",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___offsetUnsets"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__getOffset\u0028\u0029",
            "name": "__getOffset",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___getOffset"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__setOffset\u0028\u0029",
            "name": "__setOffset",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___setOffset"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__getHandler\u0028\u0029",
            "name": "__getHandler",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___getHandler"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__pushHandler\u0028\u0029",
            "name": "__pushHandler",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___pushHandler"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__pushHandlers\u0028\u0029",
            "name": "__pushHandlers",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___pushHandlers"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__pullHandler\u0028\u0029",
            "name": "__pullHandler",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___pullHandler"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__fillHandlers\u0028\u0029",
            "name": "__fillHandlers",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___fillHandlers"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__clearHandlers\u0028\u0029",
            "name": "__clearHandlers",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___clearHandlers"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__getIterator\u0028\u0029",
            "name": "__getIterator",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___getIterator"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A__toArray\u0028\u0029",
            "name": "__toArray",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method___toArray"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A____debugInfo\u0028\u0029",
            "name": "____debugInfo",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#method_____debugInfo"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#property_fillable"
        },                {
            "fqsen": "\\Handler\\HandlerTrait\u003A\u003A\u0024attributes",
            "name": "attributes",
            "summary": "",
            "url": "classes/Handler-HandlerTrait.html#property_attributes"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Handler",
            "name": "Handler",
            "summary": "",
            "url": "namespaces/handler.html"
        }            ]
);
